TypeScript error in C:/Users/Michal/WebstormProjects/Seahorse/web-app/seahorse/src/DynamicForm/FormActions/InputFormAction.tsx(44,47):
Type '{ children: string; className: string; size: string; column: true; sm: number; }' is not assignable to type '(IntrinsicAttributes & Pick<Pick<DetailedHTMLProps<LabelHTMLAttributes<HTMLLabelElement>, HTMLLabelElement>, "onChange"
| ... 255 more ... | "key"> & { ...; }, "onChange" | ... 253 more ... | "key"> & BsPrefixProps<...> & FormLabelWithColProps & { ...; }) | (IntrinsicAttributes & ... 3 more ... & { ...; })'.
  Property 'size' does not exist on type 'IntrinsicAttributes & Pick<Pick<DetailedHTMLProps<LabelHTMLAttributes<HTMLLabelElement>, HTMLLabelElement>, "onChange" | ... 255 more ... | "key"> & { ...; }, "onChange" | ... 253 more ... | "k
ey"> & BsPrefixProps<...> & FormLabelWithColProps & { ...; }'.  TS2322